### ISSUE TITLE
dateUpdated and dateCreated are returning values off by 12 hours

### ISSUE THREAD

**Issue by Brandon-Wolff** [Diversido/flutter_twilio_conversations#13]
The `dateToString` function in the `Mapper` files for both iOS and Android uses 12 hour formatting without including an AM or PM indicator. Because of this, any channel created or updated after noon appears to have been made 12 hours earlier. Changing `"yyyy-MM-dd hh:mm:ss"`  to `"yyyy-MM-dd HH:mm:ss"` fixes the problem.

**Comment by asmodeoux** [comment]
Fixed in release `1.1.2+4` ✅
