### ISSUE TITLE
onTypingStarted and onTypingEnded events 

### ISSUE THREAD

**Issue by martintrollip** [Diversido/flutter_twilio_conversations#2]
Hi @Diversido,

We're currently experiencing an issue with the `ChannelListener` on Android and IOS. Specifically we're not receiving events for `onTypingStarted` and `onTypingEnded`.

On Android, we see `MissingPluginException` with the following message: `No implementation found for method listen on channel flutter_twilio_conversations/CH6d50bca53db643779c9fce90554abxyz`.

Do you have any suggestions on how we can investigate this issue further? We would greatly appreciate any help you can provide.  I'm planning to open a PR with a fix once I have identified the issue.

Thank you for your assistance.

<details>
  <summary>Flutter doctor output</summary>

      [✓] Flutter (Channel stable, 3.3.10, on macOS 13.4 22F66 darwin-arm, locale en-ZA)
        • Flutter version 3.3.10 on channel stable at /Users/martin/Development/sdks/flutter
        • Upstream repository https://github.com/flutter/flutter.git
        • Framework revision 135454af32 (6 months ago), 2022-12-15 07:36:55 -0800
        • Engine revision 3316dd8728
        • Dart version 2.18.6
        • DevTools version 2.15.0
    
    [✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
        • Android SDK at /Users/martin/Development/sdks/android
        • Platform android-33, build-tools 32.1.0-rc1
        • ANDROID_HOME = /Users/martin/Development/sdks/android
        • Java binary at: /opt/homebrew/Cellar/openjdk@11/11.0.14.1/libexec/openjdk.jdk/Contents/Home/bin/java
        • Java version OpenJDK Runtime Environment Homebrew (build 11.0.15+0)
        • All Android licenses accepted.
    
    [✓] Xcode - develop for iOS and macOS (Xcode 14.2)
        • Xcode at /Applications/Xcode.app/Contents/Developer
        • Build 14C18
        • CocoaPods version 1.12.1
    
    [✓] Chrome - develop for the web
        • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
    
    [!] Android Studio (version 2022.1)
        • Android Studio at /Applications/Android Studio.app/Contents
        • Flutter plugin can be installed from:
          🔨 https://plugins.jetbrains.com/plugin/9212-flutter
        • Dart plugin can be installed from:
          🔨 https://plugins.jetbrains.com/plugin/6351-dart
        ✗ Unable to find bundled Java version.
        • Try updating or re-installing Android Studio.
    
    [✓] IntelliJ IDEA Community Edition (version 2023.1)
        • IntelliJ at /Applications/IntelliJ IDEA CE.app
        • Flutter plugin version 73.1.1
        • Dart plugin version 231.9065
    
    [✓] VS Code (version 1.78.2)
        • VS Code at /Applications/Visual Studio Code.app/Contents
        • Flutter extension version 3.64.0
    
    [✓] VS Code (version 1.79.0-insider)
        • VS Code at /Applications/Visual Studio Code - Insiders.app/Contents
        • Flutter extension version 3.64.0
    
    [✓] Connected device (3 available)
        • iPhone SE (3rd generation) (mobile) • 02A70EF5-EE6D-4A47-AF07-DCEB95249F47 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-2
          (simulator)
        • macOS (desktop)                     • macos                                • darwin-arm64   • macOS 13.4 22F66 darwin-arm
        • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 114.0.5735.90
    
    [✓] HTTP Host Availability
        • All required HTTP hosts are available
    
</details>

**Comment by asmodeoux** [comment]
Hi!
We should check if there's platform implementation for these methods, and if not, one should be added. A good thing to do would be to also include it into the example project to make sure it doesn't break later. We'd appreciate any help with improving the package 🙌🏻

**Comment by martintrollip** [comment]
Fixed in #3
